export const activeOrdersArray = [
  {
    orderId: '124324',
    estimatedTime: '15 mins',
    status: 'bid-accepted',
    contact: '312-232-1212',
    location: '1210 W Lexington St',
  },
  {
    orderId: '434344',
    estimatedTime: '10 mins',
    status: 'in-transit',
    contact: '434-434-5464',
    location: '1210 W Lexington St',
  },
  {
    orderId: '675435',
    estimatedTime: 'Bid unaccepted',
    status: 'bid-unaccepted',
    contact: '',
    location: '1210 W Lexington St',
  },
  {
    orderId: '535422',
    estimatedTime: '12 mins',
    status: 'in-transit',
    contact: '234-767-3477',
    location: '1210 W Lexington St',
  },
  {
    orderId: '242465',
    estimatedTime: '20 mins',
    status: 'in-transit',
    contact: '324-678-7676',
    location: '1210 W Lexington St',
  },
];

export const pastOrders = [
  {
    orderId: "123456",
    amount: "15$",
    bidType: "Single Order",
    address: "1210 W Lexingtion Street Apt 3F",
    city: "Chicago",
    drivers: "James Cameron",
  },
  {
    orderId: "345678",
    amount: "10$",
    bidType: "Hire Out",
    address: "712 S Aberdeen St Apt 3R",
    city: "Chicago",
    drivers: "Jimmy Neutron",
  },
  {
    orderId: "789101",
    amount: "20$",
    bidType: "Single Order",
    address: "1218 W Flournoy St Apt 1F",
    city: "Chicago",
    drivers: "Jack Dawson",
  },
  {
    orderId: "565433",
    amount: "30$",
    bidType: "Single Order",
    address: "821 S Miller St",
    city: "Chicago",
    drivers: "Jamie Fox",
  },
  {
    orderId: "123799",
    amount: "7$",
    bidType: "Hire Out",
    address: "1148 W Washburne Ave",
    city: "Chicago",
    drivers: "Johnny Sins",
  },
];

export const month = [
  { expenses: 1234, month: "April", delta: 30 },
  { expenses: 3356, month: "March", delta: 43 },
  { expenses: 1122, month: "February", delta: 13 },
  { expenses: 1233, month: "January", delta: 17 },
  { expenses: 1111, month: "December", delta: 27 },
  { expenses: 2222, month: "November", delta: 31 },
  { expenses: 1112, month: "October", delta: 57 },
  { expenses: 1134, month: "September", delta: 23 },
  { expenses: 4567, month: "August", delta: 52 },
];

export const driversarray = [
  {
    name: "James",
    favorite: false,
    yourOrders: 16,
    totalOrders: 600,
    rating: 4.1,
    reviews: 100,
  },
  {
    name: "Jimmy",
    favorite: true,
    yourOrders: 26,
    totalOrders: 125,
    rating: 4.2,
    reviews: 120,
  },
  {
    name: "Jack",
    favorite: true,
    yourOrders: 36,
    totalOrders: 150,
    rating: 4.3,
    reviews: 140,
  },
  {
    name: "Jamie",
    favorite: false,
    yourOrders: 46,
    totalOrders: 175,
    rating: 4.4,
    reviews: 160,
  },
  {
    name: "Johnny",
    favorite: false,
    yourOrders: 56,
    totalOrders: 200,
    rating: 4.5,
    reviews: 180,
  },
  {
    name: "Jacob",
    favorite: true,
    yourOrders: 66,
    totalOrders: 225,
    rating: 4.6,
    reviews: 200,
  },
];
