export const activeOrdersArray = [
  {
    orderId: '124324',
    estimatedTime: '15 mins',
    status: 'bid-accepted',
    contact: '312-232-1212',
    location: '1210 W Lexington St',
  },
  {
    orderId: '434344',
    estimatedTime: '10 mins',
    status: 'in-transit',
    contact: '434-434-5464',
    location: '1210 W Lexington St',
  },
  {
    orderId: '675435',
    estimatedTime: 'Bid unaccepted',
    status: 'bid-unaccepted',
    contact: '',
    location: '1210 W Lexington St',
  },
  {
    orderId: '535422',
    estimatedTime: '12 mins',
    status: 'in-transit',
    contact: '234-767-3477',
    location: '1210 W Lexington St',
  },
  {
    orderId: '242465',
    estimatedTime: '20 mins',
    status: 'in-transit',
    contact: '324-678-7676',
    location: '1210 W Lexington St',
  },
];

export const driversarray = [
  {
    name: 'James',
    favorite: false,
    yourOrders: 16,
    totalOrders: 600,
    rating: 4.1,
    reviews: 100,
  },
  {
    name: 'Jimmy',
    favorite: true,
    yourOrders: 26,
    totalOrders: 125,
    rating: 4.2,
    reviews: 120,
  },
  {
    name: 'Jack',
    favorite: true,
    yourOrders: 36,
    totalOrders: 150,
    rating: 4.3,
    reviews: 140,
  },
  {
    name: 'Jamie',
    favorite: false,
    yourOrders: 46,
    totalOrders: 175,
    rating: 4.4,
    reviews: 160,
  },
  {
    name: 'Johnny',
    favorite: false,
    yourOrders: 56,
    totalOrders: 200,
    rating: 4.5,
    reviews: 180,
  },
  {
    name: 'Jacob',
    favorite: true,
    yourOrders: 66,
    totalOrders: 225,
    rating: 4.6,
    reviews: 200,
  },
];
